-- start siuanny sequences
CREATE SEQUENCE Produtos_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE Categorias_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE Marcas_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE Solicitacao_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
-- end siuanny sequences

-- start siuanny tables
CREATE TABLE Produtos (
    id_produto INTEGER DEFAULT Produtos_seq.NEXTVAL,
    NOME VARCHAR(50),
    descricao VARCHAR(500),
    margem_lucro DECIMAL(10,2),
    id_categoria INTEGER,
    id_marca INTEGER
);

CREATE TABLE Categorias (
    id_categoria INTEGER DEFAULT Categorias_seq.NEXTVAL,
    NOME VARCHAR(50)
);

CREATE TABLE Marcas (
    id_marca INTEGER DEFAULT Marcas_seq.NEXTVAL,
    NOME VARCHAR(50)
);

CREATE TABLE Solicitacao (
    id_solicitacao INTEGER  DEFAULT Solicitacao_seq.NEXTVAL,
    data_solicitacao DATE,
    data_prevista DATE,
    data_entrega DATE,
    valor_compra DECIMAL(10,2),
    prazo_pagamento DATE,
    ID_FILIAL INTEGER,
    cnpj_fonecedor CHAR(14)
);
-- end siuanny tables

-- start siuanny constraints
ALTER TABLE Produtos ADD CONSTRAINT PK_Produtos PRIMARY KEY (id_produto);
ALTER TABLE Produtos ADD CONSTRAINT FK_Produtos_Categorias FOREIGN KEY (id_categoria) REFERENCES Categorias(id_categorias);
ALTER TABLE Produtos ADD CONSTRAINT FK_Produtos_Marcas FOREIGN KEY (id_marca) REFERENCES Marcas(id_marca);
ALTER TABLE Produtos ADD CONSTRAINT Ck_Produtos_lucro_maior_que_zero CHECK (margem_lucro > 0); 

ALTER TABLE Categorias ADD CONSTRAINT PK_Categorias PRIMARY KEY (id_categoria);

ALTER TABLE Marcas ADD CONSTRAINT PK_Marcas PRIMARY KEY (id_marca);

ALTER TABLE Solicitacao ADD CONSTRAINT PK_Solicitacao PRIMARY KEY (id_solicitacao);
ALTER TABLE Solicitacao ADD CONSTRAINT FK_Solicitacao_Filiais FOREIGN KEY (ID_FILIAL) REFERENCES Filiais(ID_FILIAL);
ALTER TABLE Solicitacao ADD CONSTRAINT FK_Solicitacao_Fornecedores FOREIGN KEY (cnpj_fornecedor) REFERENCES Fornecedores(cnpj);
-- end siuanny constraints

--start beatriz sequences
CREATE SEQUENCE CAIXAS_SEQ 
    START WITH 1 INCREMENT BY 1 NOCYCLE;
--end beatriz sequences

--start beatriz tables
CREATE TABLE CLIENTE(
    CPF CHAR(11),
    NOME VARCHAR(50)NOT NULL,
    EMAIL VARCHAR(40),
    PONTOS INTEGER
)

CREATE TABLE TELEFONE_CLIENTE(
    CPF_CLIENTE CHAR(11),
    TELEFONES CHAR(9)
)

CREATE TABLE ENDERECOS(
    CPF_CLIENTE CHAR(11),
    RUA VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(4),
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL
)

CREATE TABLE ORDEM_COMPRA(
    NOTA_FISCAL CHAR(44),
    DATA_COMPRA DATE, 
    ID_CAIXA INTEGER,
    CPF_CLIENTE CHAR(11)
)

CREATE TABLE CAIXA(
    NUM_CAIXAS INTEGER DEFAULT CAIXAS_SEQ.NEXTVAL,
    NUM_FILIAL CHAR(9) NOT NULL
)

--end beatriz tables

--start beatriz constraints
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE 
    PRIMARY KEY (CPF);

ALTER TABLE TELEFONE_CLIENTE ADD CONSTRAINT PK_TELEFONE_CLIENTE
    PRIMARY KEY (CPF_CLIENTE, TELEFONES);

ALTER TABLE ENDERECOS ADD CONSTRAINT PK_ENDERECOS
    PRIMARY KEY (CPF_CLIENTE);

ALTER TABLE ORDEM_COMPRA ADD CONSTRAINT PK_ORDEM_COMPRA
    PRIMARY KEY (NOTA_FISCAL);

-- foreign keys -- 

ALTER TABLE TELEFONE_CLIENTE ADD CONSTRAINT TELEFONES_CLIENTE_CPFCLIENTE 
    FOREIGN KEY(CPF_CLIENTE) REFERENCES CLIENTE(CPF)
INITIALLY DEFERRED DEFERRABLE

ALTER TABLE ENDERECOS ADD CONSTRAINT CPFENDERECOS_CPFCLIENTE
   	 FOREIGN KEY(CPF_CLIENTE) REFERENCES CLIENTE(CPF)
INITIALLY DEFERRED DEFERRABLE

ALTER TABLE ORDEM_COMPRA ADD CONSTRAINT COMPRAS_IDCAIXA
    FOREIGN KEY(ID_CAIXA) REFERENCES CAIXA(NUM_CAIXAS)
  INITIALLY DEFERRED DEFERRABLE

ALTER TABLE ORDEM_COMPRA ADD CONSTRAINT NOTAS_NOTASFISCAIS
    FOREIGN KEY(NOTA_FISCAL) REFERENCES NOTA_FISCAL(NUMERO_NOTA_FISCAL)
INITIALLY DEFERRED DEFERRABLE

ALTER TABLE ORDEM_COMPRA ADD CONSTRAINT ORDEM_CLIENTES
    FOREIGN KEY(CPF_CLIENTE) REFERENCES CLIENTE(CPF)
INITIALLY DEFERRED DEFERRABLE

ALTER TABLE CAIXA ADD CONSTRAINT CAIXAS_FILIAIS
    FOREIGN KEY(NUM_FILIAL) REFERENCES FILIAIS(ID_FILIAL)
INITIALLY DEFERRED DEFERRABLE

-- start mariana tables 
CREATE TABLE FUNCIONARIO (
    MATRICULA CHAR(9),
    CPF CHAR(11) NOT NULL,
    IDENTIDADE CHAR(7) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(200),
    SALARIO NUMBER(9,2),
    FUNCAO VARCHAR(40),
    CODIGO_DE_IDENTIFICACAO CHAR(9),
    GERENTE VARCHAR(50)
);

CREATE TABLE TELEFONES_FUNCIONARIOS (
    MATRICULA CHAR(9),
    TELEFONE CHAR(9)
);

CREATE TABLE FORNECEDOR (
    CNPJ CHAR(14),
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(200),
    EMAIL VARCHAR(40),
    SITE VARCHAR(30),
    IDENTIFICADOR INTEGER
);

CREATE TABLE TELEFONES_FORNECEDORES (
    CNPJ CHAR(14),
    TELEFONE CHAR(9)
);

CREATE TABLE DEPENDENTE (
    CPF CHAR(11),
    DATA_DE_NASCIMENTO DATE,
    MATRICULA CHAR(9),
    NOME VARCHAR(50) NOT NULL

);
-- end mariana tables

-- start mariana constraints
ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_MATRICULA PRIMARY KEY (MATRICULA);

ALTER TABLE TELEFONES_FUNCIONARIOS ADD CONSTRAINT PK_TELEFONES_FUNCIONARIOS PRIMARY KEY (MATRICULA, TELEFONE);

ALTER TABLE FORNECEDOR ADD CONSTRAINT PK_CNPJ PRIMARY KEY (CNPJ);

ALTER TABLE TELEFONES_FORNECEDORES ADD CONSTRAINT PK_TELEFONES_FORNECEDORES PRIMARY KEY (CNPJ, TELEFONE);

ALTER TABLE DEPENDENTE ADD CONSTRAINT PK_CPF PRIMARY KEY (CPF);

ALTER TABLE FORNECEDOR ADD CONSTRAINT FK_IDENTIFICADOR FOREIGN KEY (IDENTIFICADOR) REFERENCES CATEGORIA(IDENTIFICADOR);

ALTER TABLE TELEFONES_FORNECEDORES ADD CONSTRAINT FK_CNPJ FOREIGN KEY (CNPJ) REFERENCES FORNECEDOR(CNPJ);

ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_MATRICULA FOREIGN KEY (MATRICULA) REFERENCES FUNCIONARIO(MATRICULA);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_CODIGO_DE_IDENTIFICACAO FOREIGN KEY (CODIGO_DE_IDENTIFICACAO) REFERENCES FILIAL(CODIGO_DE_IDENTIFICACAO);
-- end mariana constraints

-- starts Guilherme sequences
CREATE SEQUENCE FILIAIL_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE SEQUENCE EQUIPAMENTO_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE;
-- ends Guilherme sequences 

-- starts Guilherme tables
CREATE TABLE FILIAL (
    CODIGO_DE_IDENTIFICACAO INTEGER DEFAULT FILIAIS_SEQ.NEXTVAL,
    NOME VARCHAR(50),
    ENDERECO VARCHAR(200),
    TELEFONE VARCHAR(13),
    ID_DO_GERENTE CHAR(9)
);

CREATE TABLE NOTA_FISCAL (
    NUMERO CHAR(44),
    CNPJ CHAR(14),
    QUANTIDADE INTEGER,
    DATA DATE,
    VALOR_POR_ITEM DECIMAL(10, 2),
    ID_DE_SOLICITACAO INTEGER
);

CREATE TABLE EQUIPAMENTO (
    IDENTIFICADOR INTEGER DEFAULT EQUIPAMENTO_SEQ.NEXTVAL,
    DESCRICAO VARCHAR(500),
    NUMERO_DO_CAIXA INTEGER,
);

CREATE TABLE REALIZA_RECLAMACAO (
    CPF CHAR(11),
    CODIGO_DE_IDENTIFICACAO INTEGER,
    DATA_E_HORA TIMESTAMP,
    DESCRICAO VARCHAR(500)
);

CREATE TABLE REALIZA_MANUTENCAO (
    IDENTIFICADOR INTEGER,
    MATRICULA CHAR(9),
    DATA_E_HORA TIMESTAMP,
    CUSTO DECIMAL(10, 2)
);
-- ends Guilherme tables

-- start Guilherme constraints
ALTER TABLE FILIAL ADD CONSTRAINT PK_FILIAL  PRIMARY KEY (CODIGO_DE_IDENTIFICACAO);
ALTER TABLE FILIAL ADD CONSTRAINT FK_FILIAL_GERENTE FOREIGN KEY (ID_GERENTE) REFERENCES FUNCIONARIO(MATRICULA);

ALTER TABLE NOTA_FISCAL ADD CONSTRAINT PK_NOTA_FISCAL PRIMARY KEY (NUMERO); 
ALTER TABLE NOTA_FISCAL ADD CONSTRAINT FK_NOTA_FISCAL_SOLICITACAO FOREIGN KEY (ID_DE_SOLICITACAO) REFERENCES SOLICITACAO(IDENTIFICADOR);

ALTER TABLE EQUIPAMENTO ADD CONSTRAINT PK_EQUIPAMENTO PRIMARY KEY (IDENTIFICADOR);
ALTER TABLE EQUIPAMENTO ADD CONSTRAINT FK_EQUIPAMENTO_ FOREIGN KEY (NUMERO_DO_CAIXA) REFERENCES CAIXA(NUMERO_DO_CAIXA);

ALTER TABLE REALIZA_RECLAMACAO ADD CONSTRAINT PK_REALIZA_RECLAMACAO PRIMARY KEY (CPF, CODIGO_DE_IDENTIFICACAO);
ALTER TABLE REALIZA_RECLAMACAO ADD CONSTRAINT FK_REALIZA_RECLAMACAO_CLIENTE FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF);
ALTER TABLE REALIZA_RECLAMACAO ADD CONSTRAINT FK_REALIZA_RECLAMACAO_FILIAL FOREIGN KEY (CODIGO_DE_IDENTIFICACAO) REFERENCES FILIAL(CODIGO_DE_IDENTIFICACAO); 

ALTER TABLE REALIZA_MANUTENCAO ADD CONSTRAINT PK_REALIZA_MANUTENCAO PRIMARY KEY (IDENTIFICADOR, MATRICULA);
ALTER TABLE REALIZA_MANUTENCAO ADD CONSTRAINT FK_REALIZA_MANUTENCAO_EQUIPAMENTO FOREIGN KEY (IDENTIFICADOR) REFERENCES EQUIPAMENTO(IDENTIFICADOR);
ALTER TABLE REALIZA_MANUTENCAO ADD CONSTRAINT FK_REALIZA_MANUTENCAO_FUNCIONARIO FOREIGN KEY (MATRICULA) REFERENCES FUNCIONARIO(MATRICULA);
-- ends Guilherme constraints
