-- star siuanny sequences
CREATE SEQUENCE Produtos_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE Categorias_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE Marcas_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE Solicitacao_seq START WITH 1 INCREMENT BY 1 NOCYCLE;
-- end siuanny sequences

-- star siuanny tables
CREATE TABLE Produtos (
    id_produto INTEGER DEFAULT Produtos_seq.NEXTVAL,
    NOME VARCHAR(50),
    descricao VARCHAR(500),
    margem_lucro DECIMAL(10,2),
    id_categoria INTEGER,
    id_marca INTEGER
);

CREATE TABLE Categorias (
    id_categoria INTEGER DEFAULT Categorias_seq.NEXTVAL,
    NOME VARCHAR(50)
);

CREATE TABLE Marcas (
    id_marca INTEGER DEFAULT Marcas_seq.NEXTVAL,
    NOME VARCHAR(50)
);

CREATE TABLE Solicitacao (
    id_solicitacao INTEGER  DEFAULT Solicitacao_seq.NEXTVAL,
    data_solicitacao DATE,
    data_prevista DATE,
    data_entrega DATE,
    valor_compra DECIMAL(10,2),
    prazo_pagamento DATE,
    ID_FILIAL INTEGER,
    cnpj_fonecedor CHAR(14)
);
-- end siuanny tables

-- start siuanny constraints
ALTER TABLE Produtos ADD CONSTRAINT PK_Produtos PRIMARY KEY (id_produto);
ALTER TABLE Produtos ADD CONSTRAINT FK_Produtos_Categorias FOREIGN KEY (id_categoria) REFERENCES Categorias(id_categorias);
ALTER TABLE Produtos ADD CONSTRAINT FK_Produtos_Marcas FOREIGN KEY (id_marca) REFERENCES Marcas(id_marca);
ALTER TABLE Produtos ADD CONSTRAINT Ck_Produtos_lucro_maior_que_zero CHECK (margem_lucro > 0); 

ALTER TABLE Categorias ADD CONSTRAINT PK_Categorias PRIMARY KEY (id_categoria);

ALTER TABLE Marcas ADD CONSTRAINT PK_Marcas PRIMARY KEY (id_marca);

ALTER TABLE Solicitacao ADD CONSTRAINT PK_Solicitacao PRIMARY KEY (id_solicitacao);
ALTER TABLE Solicitacao ADD CONSTRAINT FK_Solicitacao_Filiais FOREIGN KEY (ID_FILIAL) REFERENCES Filiais(ID_FILIAL);
ALTER TABLE Solicitacao ADD CONSTRAINT FK_Solicitacao_Fornecedores FOREIGN KEY (cnpj_fornecedor) REFERENCES Fornecedores(cnpj);
-- end siuanny constraints

--start beatriz sequences
CREATE SEQUENCE CAIXAS_SEQ 
    START WITH 1 INCREMENT BY 1 NOCYCLE;


--end beatriz sequences

--start beatriz tables
CREATE TABLE CLIENTES(
    CPF CHAR(11),
    NOME VARCHAR(50)NOT NULL,
    EMAIL VARCHAR(40),
    PONTOS INTEGER
)

CREATE TABLE TELEFONES_CLIENTES(
    CPF_CLIENTES CHAR(11),
    TELEFONES CHAR(9)
)

CREATE TABLE ENDERECOS(
    CPF_CLIENTES CHAR(11),
    RUA VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(4),
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL
)

CREATE TABLE ORDEM_COMPRAS(
    NOTA_FISCAL CHAR(44),
    DATA_COMPRA DATE, 
    ID_CAIXA INTEGER,
    CPF_CLIENTES CHAR(11)
)

CREATE TABLE CAIXAS(
    NUM_CAIXAS INTEGER DEFAULT CAIXAS_SEQ.NEXTVAL,
    NUM_FILIAL CHAR(9) NOT NULL
)

--end beatriz tables

--start beatriz constraints
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTE 
    PRIMARY KEY (CPF);

ALTER TABLE TELEFONES_CLIENTES ADD CONSTRAINT PK_TELEFONES_CLIENTES
    PRIMARY KEY (CPF_CLIENTES, TELEFONES);

ALTER TABLE ENDERECOS ADD CONSTRAINT PK_ENDERECOS
    PRIMARY KEY (CPF_CLIENTES);

ALTER TABLE ORDEM_COMPRAS ADD CONSTRAINT PK_ORDEM_COMPRAS 
    PRIMARY KEY (NOTA_FISCAL);

-- foreign keys -- 

ALTER TABLE TELEFONES_CLIENTES ADD CONSTRAINT TELEFONES_CLIENTES_CPFCLIENTE 
    FOREIGN KEY(CPF_CLIENTES) REFERENCES CLIENTES(CPF)
INITIALLY DEFERRED DEFERRABLE

ALTER TABLE ENDERECOS ADD CONSTRAINT CPFENDERECOS_CPFCLIENTE
   	 FOREIGN KEY(CPF_CLIENTES) REFERENCES CLIENTES(CPF)
INITIALLY DEFERRED DEFERRABLE

ALTER TABLE ORDEM_COMPRAS ADD CONSTRAINT COMPRAS_IDCAIXA
    FOREIGN KEY(ID_CAIXA) REFERENCES CAIXAS(NUM_CAIXAS)
  INITIALLY DEFERRED DEFERRABLE

ALTER TABLE ORDEM_COMPRAS ADD CONSTRAINT NOTAS_NOTASFISCAIS
    FOREIGN KEY(NOTA_FISCAL) REFERENCES NOTA_FISCAL(NUMERO_NOTA_FISCAL)
INITIALLY DEFERRED DEFERRABLE

ALTER TABLE ORDEM_COMPRAS ADD CONSTRAINT ORDEM_CLIENTES
    FOREIGN KEY(CPF_CLIENTES) REFERENCES CLIENTES(CPF)
INITIALLY DEFERRED DEFERRABLE

ALTER TABLE CAIXAS ADD CONSTRAINT CAIXAS_FILIAIS
    FOREIGN KEY(NUM_FILIAL) REFERENCES FILIAIS(ID_FILIAL)
INITIALLY DEFERRED DEFERRABLE

--end Beatriz constraints